### ISSUE TITLE
metamorph: use and combination of reset, flushWith and sameEntity attributes

### ISSUE THREAD

**Issue by guenterh** [metafacture/metafacture-documentation#4] opened 2015-12-20 19:39 UTC
- since some time I'm struggling with the appropriate use of the `reset`, `flushWith` and `sameEntity` attributes on the various collector artefacts but also on the entity tag of Metamorph
- Mostly after some try and error definitions I got a result which was the one I expected but I had difficulties to explain the clear differences between the examples
- Hopefully I can now provide a distinguished example which might be helpful to discuss the mechanisms behind the implementation
- [This directory](https://github.com/guenterh/mfDocProc/tree/master/src/main/resources/transformation/searchDocs/questions/difference_concat_combine_morph_attributes) contains the examples.
- `flushWith` and `reset=true` is used in the [MorphScript_case_1](https://github.com/guenterh/mfDocProc/blob/master/src/main/resources/transformation/searchDocs/questions/difference_concat_combine_morph_attributes/combine.concat.reset.true.morph.xml) whereas `sameEntity=true` and `reset=false`  delivers the correct result in this [Morph script_case_2](https://github.com/guenterh/mfDocProc/blob/master/src/main/resources/transformation/searchDocs/questions/difference_concat_combine_morph_attributes/combine.same.entity.no.reset.morph.xml) 
- the output files are for [case 1](https://github.com/guenterh/mfDocProc/blob/master/src/main/resources/transformation/searchDocs/questions/difference_concat_combine_morph_attributes/combine.concat.reset.true.json) and [case 2](https://github.com/guenterh/mfDocProc/blob/master/src/main/resources/transformation/searchDocs/questions/difference_concat_combine_morph_attributes/combine.same.entity.json) 
- it seems `combine` uses the `sameEntity=true` attribute for collecting the various values of an `Entity` in combination with an `If` Statement (and no inside collectors) while `concat` needs the `flushWith` Attribute in combination with `IF` and `combine` with `reset=true` attribute as the outer collector
- During our get Together meeting in HH I already mentioned my troubles with this and a helpful voice in the audience (I couldn't see as Skype participant... (edit: me,@dr0i)) was optimistic for being able to give more background infomation
- By the way these examples are part of my attempt to transform our XSLT based transformations for Solr SearchDocuments into a  Metafacture/Metamorph implementations. My main motivation for this is the question: Where are the limits and differences of Metamorph compared to traditional XSLT procedures. If you are interested how it looks like as XSLT you can find it [here](https://github.com/guenterh/mfDocProc/blob/master/src/main/resources/transformation/gh/swissbib.solr.vufind2.xsl#L612)   Hints are welcome if you know more elegant possibilities to express match ranges matches(@code, '[b-su-z8]') in XSLT compared to the way I have [done this](https://github.com/guenterh/mfDocProc/blob/master/src/main/resources/transformation/searchDocs/questions/difference_concat_combine_morph_attributes/combine.same.entity.no.reset.morph.xml#L10) 

Thanks for any replies!!

Günter

**Comment by dr0i** [comment] 2016-11-18 13:53
> Hints are welcome if you know more elegant possibilities to express match ranges matches(@code, '[b-su-z8]') in XSLT compared to the way I have

Not exactly sure but if you meant to abbreviate  this:

    <data source="811??.b|811??.c|811??.d" />

you can use character classes:

      <data source="811??.[bcd]" />

**Comment by dr0i** [comment] 2016-11-18 15:22
Re: case1 vs. case2:
A bit complex, this. I admit to not totally forsee the result of a complex  combination of attributes and their parameters myself! So at that point I just modify&run&test until the result is satisfactory.

I don't understand what the problem is:
Since the result of the two cases are also very different (`case1`: every matched field of all entities are _entity-indistinguishable_ put into a set, while `case2` puts one concatenated string _per entity_ into the set) you evidently use two different approaches.

Nevertheless here some remarks:
In `case1` you use `<data source="950??.e"/>` in the `concat` section while flushing with (in principle) every `950-subfield` (I think). As `950??.e` happens to be the last entry all 950-entities and must be concatenated before the concatenated string is flushed ("saturation" - I _think_ this is so, not exactly sure) the "flushing" coincides with what would be better declared as `... flushWith="950??.e" >` (because of the clearness of it).

It's sometimes hard to explain and understand complex data transformations, I know. I would find it easier if you would have a question like "I have thos data and want this outcome - how to do it?". But I gather you want more of the deeper understanding which I find hard for myself. 
Maybe you haven't read http://b3e.net/metamorph-book/latest/datamodel.html yet? I haven't yet - seems to be interesting.

**Comment by dr0i** [comment] 2020-09-17 13:49
Closing this. Note that some of the problems described here may be solved by newer documentation at https://github.com/metafacture/metafacture-core/wiki/Metamorph-Cookbook.

**Closed by dr0i** 2020-09-17 13:49 UTC
